# Generated by Django 5.2.12 on 2026-06-09 18:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PrivacySettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_visibility', models.CharField(choices=[('public', 'Public Account - Everyone can find you'), ('private', 'Private Account - Only followers can see content')], default='public', help_text='Controls if your account can be found by other users', max_length=20)),
                ('followers_visibility', models.CharField(choices=[('only_me', 'Only Me'), ('followers', 'Followers Only'), ('everyone', 'Everyone')], default='only_me', help_text='Who can see your followers list', max_length=20)),
                ('following_visibility', models.CharField(choices=[('only_me', 'Only Me'), ('followers', 'Followers Only'), ('everyone', 'Everyone')], default='only_me', help_text='Who can see who you are following', max_length=20)),
                ('voting_activity_visibility', models.CharField(choices=[('hidden', 'Hidden From Everyone (Recommended)'), ('followers', 'Followers Only'), ('public', 'Everyone')], default='hidden', help_text='Who can see your voting activity', max_length=20)),
                ('poll_activity_visibility', models.CharField(choices=[('hidden', 'Hidden From Everyone (Recommended)'), ('followers', 'Followers Only'), ('public', 'Everyone')], default='hidden', help_text='Who can see your poll creation activity', max_length=20)),
                ('show_follower_notifications', models.BooleanField(default=True)),
                ('show_poll_notifications', models.BooleanField(default=True)),
                ('show_activity_notifications', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='privacy_settings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Privacy Settings',
                'verbose_name_plural': 'Privacy Settings',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True, default='', max_length=500)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='profiles/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='account_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Follow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('follower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='following', to=settings.AUTH_USER_MODEL)),
                ('following', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['follower', '-created_at'], name='accounts_fo_followe_592424_idx'), models.Index(fields=['following', '-created_at'], name='accounts_fo_followi_0cee87_idx')],
                'unique_together': {('follower', 'following')},
            },
        ),
    ]
