# Generated by Django 5.2.12 on 2026-06-09 18:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_poll_created_by_organization_poll_description_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='vote',
            name='is_anonymous',
            field=models.BooleanField(default=True),
        ),
        migrations.AddIndex(
            model_name='vote',
            index=models.Index(fields=['user', '-voted_at'], name='polls_vote_user_id_e9eaaa_idx'),
        ),
        migrations.AddIndex(
            model_name='vote',
            index=models.Index(fields=['poll', '-voted_at'], name='polls_vote_poll_id_d3abaf_idx'),
        ),
    ]
